Save to library
drupal-media/media pull request #27
Opened 2016-09-30 20:17 UTC by isthegeek

2016-10-03 07:12 UTC, slashrsm requested changes

2016-10-03 07:12 UTC, slashrsm commented on config/install/core.entity_form_display.media.document.default.yml
> +      display_label: false
Let's use field label as the checkbox label. Applies to all bundles.

2016-10-10 18:49 UTC, vijaynandwani commented on config/install/core.entity_form_display.media.document.default.yml
> +      display_label: false
Done.

2016-10-11 19:51 UTC, slashrsm approved these changes

2016-10-11 19:52 UTC, merged

2016-10-11 19:52 UTC, slashrsm commented
Merged. Thanks!